function afficherMessage() {
    document.getElementById("message").innerHTML = `
    Passionné par l’informatique et les nouvelles technologies,
    je suis une personne sérieuse, motivée et toujours prête à apprendre.
    J’aime relever de nouveaux défis, travailler en équipe
    et partager mes connaissances avec les autres.

    Mon objectif est de devenir un professionnel compétent
    dans le domaine du développement et de la gestion des systèmes d’information,
    tout en continuant à me perfectionner dans l’analyse des données.

    À travers ce site, je souhaite présenter mon parcours,
    mes compétences et mes projets, et créer des opportunités
    de collaboration et d’évolution professionnelle.
    `;
}